name: Continuous Integration

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'LICENSE'
      - '**/*.png'
      - '**/.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test test/RecaptchaDotNet.AspNetCore.Mvc.Tests.Unit/RecaptchaDotNet.AspNetCore.Mvc.Tests.Unit.csproj --no-restore --verbosity normal